### ISSUE TITLE
32x32 tiles

### ISSUE THREAD

**Issue by HengSunn** [David-schutte/Project-ITs-in-the-game#4]
![1639069088979](https://user-images.githubusercontent.com/74597305/145441731-f09b3dc2-48bf-48a7-96b0-f7ddfaeb5088.png)
![1639060984385](https://user-images.githubusercontent.com/74597305/145437075-9908c961-c1e0-4b96-a436-059aef4966e9.png)
![1639063286735](https://user-images.githubusercontent.com/74597305/145437082-a7fbfc3b-622b-402c-942e-08b59e4820eb.png)
![1639063540088](https://user-images.githubusercontent.com/74597305/145437089-3447024a-3bd4-475a-b689-07b5b39c22d6.png)
![1639063761368](https://user-images.githubusercontent.com/74597305/145437099-58221abe-fbbe-460d-9d1d-19154e9f6bfd.png)
![1639064037725](https://user-images.githubusercontent.com/74597305/145437106-7d08681c-7e53-4b7f-8327-3fb20c2b2338.png)
![1639064217883](https://user-images.githubusercontent.com/74597305/145437115-c725d576-a2b2-4ec5-8308-b2fe298d803f.png)
![1639065064056](https://user-images.githubusercontent.com/74597305/145437121-15ff93cd-29dd-405b-9b50-5f44303d460f.png)
![1639066832458](https://user-images.githubusercontent.com/74597305/145437191-3bff8b9d-455c-4f83-9f17-baf2169b26ef.png)

**Comment by Casb02** [comment]
added!
