### ISSUE TITLE
Kopje koffie?

### ISSUE THREAD

**Issue by HengSunn** [David-schutte/Project-ITs-in-the-game#5]
![IMG_23122021_122404_(32_x_32_pixel)](https://user-images.githubusercontent.com/74597305/147233696-90bd88f0-b7e6-4fcd-9ade-83a5932316e5.png)

![1639066928308](https://user-images.githubusercontent.com/74597305/145437645-45f90e86-6edb-4ba2-acfa-1c68c09754fa.png)

**Comment by Casb02** [comment]
Added!
